# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-13 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jaringan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Psd', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('Orkom', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('SistemOperasi', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('PrakSistemOperasi', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('Komdat', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('JaringanKomputer', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('PrakJaringanKomputer', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
            ],
            options={
                'db_table': 'jaringan',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(blank=True, max_length=100, null=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('LAKI-LAKI', 'LAKI-LAKI'), ('PEREMPUAN', 'PEREMPUAN')], default='LAKI-LAKI', max_length=20)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('agama', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'mahasiswa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMK', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('GrafikaKomputer', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('PrakGrafikaKomputer', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multimedias', to='orm.Mahasiswa')),
            ],
            options={
                'db_table': 'multimedia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlgoritmaDanPemrograman', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('PrakAlgoritmaDanPemrograman', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('PTI', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('StrukturData', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('SistemBasisData', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('PrakSistemBasisData', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('Pemrograman1', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('PrakPemrograman1', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('SistemInformasi', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('Pemrograman2', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('PrakPemrograman2', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('Adpl', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('ArtificialIntelligent', models.CharField(choices=[('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='E', max_length=2)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rpls', to='orm.Mahasiswa')),
            ],
            options={
                'db_table': 'rpl',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tesdasar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NilaiMultimedia', models.CharField(max_length=2, null=True)),
                ('NilaiJaringan', models.CharField(max_length=2, null=True)),
                ('NilaiRPL', models.CharField(max_length=2, null=True)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tesdasars', to='orm.Mahasiswa')),
            ],
            options={
                'db_table': 'tesdasar',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='jaringan',
            name='mahasiswa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jaringans', to='orm.Mahasiswa'),
        ),
    ]
